quotes_website/quotes/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'quotes'

urlpatterns = [
    path('', views.main, name='root'),
    path('<int:page>', views.main, name='root_paginate'),
    path('author/<str:author>', views.get_author, name='get_author'),
    path('add/quote', views.add_quote, name='add_quote'),
    path('add/author', views.add_author, name='add_author'),
    path('add/tag', views.add_tag, name='add_tag'),
    path('delete/author', views.delete_author, name='delete_author'),
    path('delete_quote/<int:quote_id>', views.delete_quote, name='delete_quote'),
    path('delete/tag', views.delete_tag, name='delete_tag'),
    path('tag/<str:tag>/page/<int:page>', views.get_tag, name='get_tag'),
]

quotes_website/quotes_website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include('users.urls')),
]

quotes_website/users/urls.py
from django.urls import path
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='register'),
    path('login/', views.signinuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

quotes_website/quotes/models.py
from django.db import models


class Author(models.Model):
    fullname = models.CharField(max_length=50, null=False)
    born_date = models.CharField(max_length=100)
    born_location = models.CharField(max_length=200)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.fullname

class Tag(models.Model):
    tag = models.CharField(max_length=50, null=False, unique=True)

    def __str__(self):
        return self.tag

class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, null=True, default=None)
    created_at = models.DateTimeField(auto_now_add=True)

quotes_website/quotes/forms.py
from typing import Any
from django.forms import ModelForm, CharField, TextInput, Textarea, ModelChoiceField, ModelMultipleChoiceField, CheckboxSelectMultiple
from .models import Quote, Author, Tag

class QuoteForm(ModelForm):
    quote = CharField(widget=Textarea(attrs={"class": "form-control", "rows": "5"}), required=True)

    author = ModelChoiceField(
        queryset=Author.objects.all().order_by("fullname"),
        empty_label="Choose author",
        required=True
    )

    tags = ModelMultipleChoiceField(
        queryset=Tag.objects.all().order_by("tag"),
        widget=CheckboxSelectMultiple(attrs={"size": "12"}))
    
    class Meta:
        model = Quote
        fields = ["quote", "author", "tags"]


class AuthorForm(ModelForm):
    fullname = CharField(
        max_length=50,
        widget=TextInput(attrs={"class": "form-control"}), required=True)
    
    born_date = CharField(
        max_length=50,
        widget=TextInput(attrs={"class": "form-control"}), required=True)
    
    born_location = CharField(
        max_length=150,
        widget=TextInput(attrs={"class": "form-control"}), required=True)
    
    description = CharField(widget=Textarea(attrs={"class": "form-control"}), required=True)

    class Meta:
        model = Author
        fields = ["fullname", "born_date", "born_location", "description"]


class TagForm(ModelForm):
    tag = CharField(
        max_length=50,
        widget=TextInput(attrs={"class": "form-control"}), required=True)
    
    class Meta:
        model = Tag
        fields = ["tag",]

class DeleteTagForm(ModelForm):
    tag = CharField(
        max_length=50,
        widget=TextInput(attrs={"class": "form-control"}), required=True)
    
    class Meta:
        model = Tag
        fields = ["tag",]


class DeleteAuthorForm(ModelForm):
    fullname = CharField(
        max_length=50,
        widget=TextInput(attrs={"class": "form-control"}), required=True)
    
    class Meta:
        model = Author
        fields = ["fullname",]

quotes_website/quotes/views.py
import collections

from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import QuoteForm, AuthorForm, DeleteAuthorForm, TagForm, DeleteTagForm
from .models import Quote, Author, Tag
# Create your views here.

def get_top_10_tags():
    quotes = Quote.objects.all()
    all_tags = []
    for quote in quotes:
        for tag in quote.tags.all():
            all_tags.append(tag.tag)
    tags_count = collections.Counter(all_tags)
    most_tags = tags_count.most_common(10)
    top_10_tags = []
    for tag in most_tags:
        top_10_tags.append(tag[0])
    return top_10_tags

def main(request, page=1):
    quotes = Quote.objects.all()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_page = paginator.page(page)
    top_10_tags = get_top_10_tags()
    return render(request, 'quotes/index.html', context={'title': 'Quotes to Scrape', 'quotes': quotes_page,
                                                         'top_10_tags': top_10_tags, 'current_page': page})

def get_author(request, author):
    author_fullname = author.split('-')[-1]
    author = Author.objects.filter(fullname__contains=author_fullname)[0]
    top_10_tags = get_top_10_tags()
    return render(request, 'quotes/get_author.html', context={'title': 'Quotes to Scrape', 'author': author,
                                                              'top_10_tags': top_10_tags})

@login_required
def add_quote(request):
    if request.method == "POST":
        form = QuoteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")
    else:
        quote_form = QuoteForm()

    return render(request, "quotes/add_quote.html", {"quote_form": quote_form})

@login_required
def add_author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")
    else:
        author_form = AuthorForm()

    return render(request, "quotes/add_author.html", {"author_form": author_form})

@login_required
def add_tag(request):
    if request.method == "POST":
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")
    else:
        tag_form = TagForm()

    return render(request, "quotes/add_tag.html", {"tag_form": tag_form})

@login_required
def delete_quote(request, quote_id):
    quote = Quote.objects.get(id=quote_id)
    quote.delete()
    return redirect(to='quotes:root')

@login_required
def delete_author(request):
    del_author_form = DeleteAuthorForm()
    if request.method == "POST":
        form = DeleteAuthorForm(request.POST)
        if form.is_valid():
            author = Author.objects.filter(fullname=form.cleaned_data['fullname'])[0]
            author.delete()
            return redirect(to="quotes:root")

    return render(request, "quotes/delete_author.html", {"del_author_form": del_author_form})

@login_required
def delete_tag(request):
    delete_tag_form = TagForm()
    if request.method == "POST":
        form = TagForm(request.POST)
        if form.is_valid():
            tag = Tag.objects.filter(tag=form.cleaned_data['tag'])[0]
            tag.delete()
            return redirect(to="quotes:root")

    return render(request, "quotes/delete_tag.html", {"delete_tag_form": delete_tag_form})

def get_tag(request, tag, page=1):
    tag_ = Tag.objects.get(tag=tag)
    quotes = Quote.objects.filter(tags=tag_.id)
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_page = paginator.page(page)
    tag_url = f'tag/{tag}/page'
    top_10_tags = get_top_10_tags()
    return render(request, 'quotes/index.html', context={'title': 'Quotes to Scrape', 'quotes': quotes_page, 
                                                         'tag_url': tag_url, 'current_page': page, 'top_10_tags': top_10_tags})

quotes_website/quotes/templates/quotes/add_author.html
{% extends "quotes/base.html" %}

{% block content %}

<h1>Add Author</h1>
<form action="{% url 'quotes:add_author' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-control">Fullname</label>
        {{author_form.fullname}}
        <label class="form-control">Born date</label>
        {{author_form.born_date}}
        <label class="form-control" size="12">Born location</label>
        {{author_form.born_location}}
        <label class="form-control" size="12">Description</label>
        {{author_form.description}}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>

{% endblock %}

quotes_website/quotes/templates/quotes/add_quote.html
{% extends "quotes/base.html" %}

{% block content %}

<h1>Add Quote</h1>
<form action="{% url 'quotes:add_quote' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-control">Quote</label>
        {{quote_form.quote}}
        <label class="form-control">Author</label>
        {{quote_form.author}}
        <label class="form-control" size="12">Tags</label>
        {{quote_form.tags}}
    </div>
    <!-- <div class="mb-3">
        <h4>Author</h4>
        <label class="form-label">Fullname</label>
        {{author_form.fullname}}
        <label class="form-label">Born date</label>
        {{author_form.born_date}}
        <label class="form-label">Born location</label>
        {{author_form.born_location}}
        <label class="form-label">Description</label>
        {{author_form.description}}
    </div> -->
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

quotes_website/quotes/templates/quotes/add_tag.html
{% extends "quotes/base.html" %}

{% block content %}

<h1>Add Tag</h1>
<form action="{% url 'quotes:add_tag' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-control">Tag name</label>
        {{tag_form.tag}}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>

{% endblock %}

quotes_website/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/main.css' %}">
    <title>{{title}}</title>
</head>

<body>
    <div class="container">
        <div class="row header-box pt-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                {% if user.is_authenticated %}
                <p>
                    <a href="{% url 'users:logout' %}" class="btn btn-primary">Logout</a>
                    <a href="{% url 'quotes:add_quote' %}" class="btn btn-primary">Add quote</a>
                    <a href="{% url 'quotes:add_author' %}" class="btn btn-primary">Add author</a>
                    <a href="{% url 'quotes:add_tag' %}" class="btn btn-primary">Add Tag</a>
                    <a href="{% url 'quotes:delete_author' %}" class="btn btn-danger">Delete author </a>
                    <a href="{% url 'quotes:delete_tag' %}" class="btn btn-danger">Delete tag </a>
                </p>
                <p>
                    {% else %}
                    <a href="{% url 'users:login' %}" class="btn btn-primary">LogIn</a>
                    <a href="{% url 'users:register' %}" class="btn btn-primary">SignUp</a>
                </p>
                {% endif %}
            </div>
        </div>
        <div class="row">
            {% block content %}

            {% endblock %}
        </div>
    </div>
    <!-- <footer class="footer">
        <div class="container">
            <p class="text-muted">
                Quotes by: <a href="https://www.goodreads.com/quotes">GoodReads.com</a>
            </p>
            <p class="copyright">
                Made with <span class="zyte">❤</span> by <a class="zyte" href="https://www.zyte.com">Zyte</a>
            </p>
        </div>
    </footer> -->
</body>

</html>

quotes_website/quotes/templates/quotes/delete_author.html
{% extends "quotes/base.html" %}

{% block content %}
{% if messages %}
    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %} role="alert">
        {{message}}
      </div>    
    {% endfor %}
{% endif %}

{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {{form.non_field_errors}}
{% endif %}
<h1>Delete Author</h1>
<form action="{% url 'quotes:delete_author' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-control">Fullname</label>
        {{del_author_form.fullname}}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

quotes_website/quotes/templates/quotes/delete_tag.html
{% extends "quotes/base.html" %}

{% block content %}

<h1>Delete Tag</h1>
<form action="{% url 'quotes:delete_tag' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-control">Tag name</label>
        {{delete_tag_form.tag}}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

quotes_website/quotes/templates/quotes/get_author.html
{% extends "quotes/base.html" %}
{% block content %}

<div class="author-details">
    <h3 class="author-title">{{ author.fullname }}</h3>
    <p><strong>Born:</strong> <span class="author-born-date">{{ author.born_date }}</span>
       <span class="author-born-location">{{ author.born_location }}</span></p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{ author.description }}
    </div>
</div>
{% endblock %}

quotes_website/quotes/templates/quotes/index.html
{% extends "quotes/base.html" %} {% load extract_tags %} {% load extract_author_name %}

{% block content %}

<div class="col-md-8">
    {% for quote in quotes %}
    <div class="quote" itemtype="http://schema.org/CreativeWork">
        {% if user.is_authenticated %}
        <a href="{% url 'quotes:delete_quote' quote.id %}" class="btn btn-danger">Delete quote </a>
        {% endif %}
        <span class="text" itemprop="text">{{quote.quote}}</span>
        <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
            <a href="/author/{{quote.author.fullname|fullname}}">(about)</a>
        </span>
        <div class="tags">
            Tags:
            <meta class="keywords" itemprop="keywords" content="{{quote.tags.all|tags}}">
            {% for tag in quote.tags.all %}
            <a class="tag" href="/tag/{{tag.tag}}/page/{{ current_page }}">{{tag.tag}}</a>
            {% endfor %}
        </div>
    </div>
    {% endfor %}
    <nav>
        <ul class="pager">
            {% if quotes.has_previous %}
            <li class="previous">
                <a class="{% if not quotes.has_previous %} disabled {% endif %}" 
                   href="{% if quotes.has_previous %} 
                   {% if tag_url %} {{quotes.previous_page_number}} 
                   {% else %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% endif %}
                   {% else %} # {% endif %}">
                    <span aria-hidden="true">←</span> Previous</a>
            </li>
            {% endif %}
            {% if quotes.has_next %}
            <li class="next">
                <a class="{% if not quotes.has_next %} disabled {% endif %}" 
                   href="{% if quotes.has_next %} 
                         {% if tag_url %} {{quotes.next_page_number}} 
                         {% else %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% endif %}
                        {% else %} # {% endif %}">
                    Next <span aria-hidden="true">→</span></a>
            </li>
            {% endif %}
        </ul>
    </nav>
</div>
<div class="col-md-4 tags-box">

    <h2>Top Ten tags</h2>
    {% for tag in top_10_tags %}
    <span class="tag-item">
        <a class="tag" style="font-size: 28px" href="/tag/{{ tag }}/page/1">{{ tag }}</a>
    </span>
    {% endfor %}
</div>
{% endblock %}