quotes_website/quotes_website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include('users.urls')),
]

quotes_website/users/urls.py
from django.urls import path
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='register'),
    path('login/', views.signinuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

quotes_website/users/models.py
from django.db import models

# Create your models here.

quotes_website/users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import CharField, TextInput, PasswordInput, EmailField, EmailInput


class RegisterForm(UserCreationForm):
    username = CharField(max_length=100, widget=TextInput())
    email = EmailField(widget=EmailInput())
    password1 = CharField(max_length=20, min_length=8, widget=PasswordInput())
    password2 = CharField(max_length=20, min_length=8, widget=PasswordInput())

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


class LoginForm(AuthenticationForm):
    # username = CharField(max_length=100, required=True, widget=TextInput())
    email = EmailField(widget=EmailInput())
    password = CharField(max_length=20, min_length=8, required=True, widget=PasswordInput())

    class Meta:
        model = User
        fields = ("email", "password")

quotes_website/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.views import PasswordResetView
from django.urls import reverse_lazy

from .forms import RegisterForm, LoginForm
# Create your views here.

def signupuser(request):
    if request.user.is_authenticated:
         redirect(to='quotes:root')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='users:login')
        else:
            return render(request, 'users/signup.html', context={"form": form})

    return render(request, 'users/signup.html', context={"form": RegisterForm()})

def signinuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotes:root')
    
    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, "User's name or password didn't match")
            return redirect(to='users:login')
        login(request, user)
        return redirect(to='quotes:root')
    return render(request, 'users/signin.html', context={'form': LoginForm()})

class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='quotes:root')

quotes_website/users/templates/users/password_reset.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

quotes_website/users/templates/users/password_reset_complete.html
{% extends "quotes/base.html" %}

{% block content %}

    <h2>Password reset complete!</h2>

{% endblock %}

quotes_website/users/templates/users/password_reset_confirm.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

quotes_website/users/templates/users/password_reset_done.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

quotes_website/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>Python Developer's team</p>
{% endautoescape %}

quotes_website/users/templates/users/signin.html
{% extends "quotes/base.html" %}

{% block content %}

<h1>Sign In</h1>

{% if messages %}
    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %} role="alert">
        {{message}}
      </div>    
    {% endfor %}
{% endif %}

{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {{form.non_field_errors}}
  </div>
{% endif %}

<form method="post">
    {% csrf_token %}
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Username</label>
            {{form.username}}
        </div>
        <span>{{form.errors.username}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Password</label>
            {{form.password}}
        </div>
        <span>{{form.errors.password}}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
    <div class="small text-center">
        <a href="{% url 'users:password_reset' %}" class="text-center"><i>Forgot Password?</i></a>
    </div>
</form>

{% endblock %}

quotes_website/users/templates/users/signup.html
{% extends "quotes/base.html" %}
{% block  content %}

<h1>Sign Up</h1>
<form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Username</label>
            {{form.username}}
        </div>
        <span>{{form.errors.username}}</span>
    </div>
    <div>
        <label> Email:
            {{ form.email }}
        </label>
        <span>{{ form.errors.email }}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Password</label>
            {{form.password1}}
        </div>
        <span>{{form.errors.password1}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Confirm password</label>
            {{form.password2}}
        </div>
        <span>{{form.errors.password2}}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}